// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package netapitest contains autogenerated mocks.
package netapitest

import "github.com/stretchr/testify/mock"

import "github.com/shoenig/ssh-key-sync/internal/ssh"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetKeys provides a mock function with given fields: user
func (mockerySelf *Client) GetKeys(user string) ([]ssh.Key, error) {
	ret := mockerySelf.Called(user)

	var r0 []ssh.Key
	if rf, ok := ret.Get(0).(func(string) []ssh.Key); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ssh.Key)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
