// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package configtest contains autogenerated mocks.
package configtest

import "github.com/shoenig/ssh-key-sync/internal/config"
import "github.com/stretchr/testify/mock"

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// Load provides a mock function with given fields:
func (mockerySelf *Loader) Load() (config.Options, error) {
	ret := mockerySelf.Called()

	var r0 config.Options
	if rf, ok := ret.Get(0).(func() config.Options); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.Options)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
