// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package githubtest contains autogenerated mocks.
package githubtest

import "indeed/gophers/3rdparty/p/github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetKeys provides a mock function with given fields: user
func (mockerySelf *Client) GetKeys(user string) ([]string, error) {
	ret := mockerySelf.Called(user)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
