package command

import (
	"os"
	"strings"
	"time"

	"github.com/shoenig/ssh-key-sync/internal/ssh"
)

func generateFileContent(keys []ssh.Key, now time.Time) string {
	var sb strings.Builder

	formattedTime := now.Format(time.RFC1123)
	sb.WriteString("# Autogenerated by ssh-key-sync on " + formattedTime + "\n\n")

	for _, key := range keys {
		if key.Managed {
			sb.WriteString("# managed by ssh-key-sync\n")
		}
		sb.WriteString(key.Value)
		if key.User != "" && key.Host != "" {
			sb.WriteString(" ")
			sb.WriteString(key.User)
			sb.WriteString("@")
			sb.WriteString(key.Host)
		}
		sb.WriteString("\n\n")
	}

	return sb.String()
}

// write to authorized_keys file
func writeToFile(file, content string) error {
	return os.WriteFile(file, []byte(content), 0600)
}
