// Author hoenig

package command

import (
	"bytes"
	"time"

	"github.com/shoenig/ssh-key-sync/internal/ssh"
)

func generateFileContent(keys []ssh.Key, now time.Time) string {
	var buf bytes.Buffer

	formattedTime := now.Format(time.RFC1123)
	buf.WriteString("# Autogenerated by ssh-key-sync on " + formattedTime + "\n\n")

	for _, key := range keys {
		if key.Managed {
			buf.WriteString("\n# managed by ssh-key-sync\n")
		}
		buf.WriteString(key.Value)
		if key.User != "" && key.Host != "" {
			buf.WriteString(" ")
			buf.WriteString(key.User)
			buf.WriteString("@")
			buf.WriteString(key.Host)
		}
		buf.WriteString("\n")
	}

	return buf.String()
}
