name: Run CI Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches:
      - 'main'
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-26
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Show System
        run: |
          just sysinfo
      - name: Run Tests
        run: |
          just init tidy lint tests
